stages:
  - build

build-debug-apk:
  stage: build
  image: mingc/android-build-box:latest
  script:
    - chmod +x ./gradlew
    - ./gradlew assembleDebug
  artifacts:
    name: "proxy-exit-debug-${CI_COMMIT_SHORT_SHA}"
    paths:
      - app/build/outputs/apk/debug/app-debug.apk
    expire_in: 1 week
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - changes:
        - app/**/*
        - build.gradle
        - settings.gradle

build-release-apk:
  stage: build
  image: mingc/android-build-box:latest
  script:
    - echo "$KEYSTORE_BASE64" | base64 -d > release.jks
    - chmod +x ./gradlew
    - ./gradlew assembleRelease
  artifacts:
    name: "proxy-exit-release-${CI_COMMIT_TAG}"
    paths:
      - app/build/outputs/apk/release/app-release.apk
    expire_in: never
  rules:
    - if: $CI_COMMIT_TAG

build-docker-image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - docker build -t "$CI_REGISTRY_IMAGE:latest" .
    - docker push "$CI_REGISTRY_IMAGE:latest"
  rules:
    - changes:
        - server/src/main/java/com/github/vgaj/proxy/ProxyServer.java
        - LICENSE
        - Dockerfile
